services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12334
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  microservice-user:
    build:
      context: ./backend
      dockerfile: microservice-user/Dockerfile
    container_name: microservice-user
    ports:
      - "8090:8090"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://host.docker.internal:8888
    depends_on:
      - postgres
      

  microservice-publication:
    build:
      context: ./backend
      dockerfile: microservice-publication/Dockerfile
    container_name: microservice-publication
    ports:
      - "9090:9090"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://host.docker.internal:8888
    depends_on:
      - postgres
      

  microservice-eureka:
    build:
      context: ./backend
      dockerfile: microservice-eureka/Dockerfile
    container_name: microservice-eureka
    ports:
      - "8761:8761"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://host.docker.internal:8888
      

  microservice-gateway:
    build:
      context: ./backend
      dockerfile: microservice-gateway/Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://host.docker.internal:8888

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - VITE_API_BASE_URL=http://microservice-gateway:8080
    ports:
      - "80:80"
    depends_on:
      - microservice-gateway

volumes:
  postgres_data: