server:
  port: 9090


spring:
  application:
    name: microservice-publication
  datasource:
    url: jdbc:postgresql://postgres:5432/publication
    username: postgres
    password: 12334
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    database: postgresql

eureka:
  instance:
    hostname: microservice-publication
  client:
    service-url:
      defaultZone: http://microservice-eureka:8761/eureka

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000