server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: users
          uri: http://host.docker.internal:8090
          predicates:
            - Path=/user/**
          filters:
            - JwtValidation
        - id: auth
          uri: http://host.docker.internal:8090
          predicates:
            - Path=/auth/**
        - id: posts
          uri: http://host.docker.internal:9090
          predicates:
            - Path=/post/**
          filters:
            - JwtValidation
        - id: comments
          uri: http://host.docker.internal:9090
          predicates:
            - Path=/comment/**
          filters:
            - JwtValidation