server:
  port: 8888

spring:
  profiles:
    active: git
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KevinRinconN/service-configuration