server:
  port: 9090

spring:
  application:
    name: microservice-publication
  datasource:
    url: jdbc:postgresql://localhost:5432/post
    username: postgres
    password: Pfdk?09.26
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    database: postgresql

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka